
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class company extends javax.swing.JFrame {

    /**
     * Creates new form company
     */
    public company() {
        initComponents();
        loaddata();
        lblcid.setVisible(false);
        txtcid.setVisible(false);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        
    }
    
    public void loaddata()
    {
     DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
     jTable1.setModel(model);
     model.setRowCount(0);
     Object row[]=new Object[2];
     try
        {
            Connection con;
            Statement stmt;
            String uid="root";
            String pwd="";
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
            stmt=con.createStatement();
            String qry="SELECT * FROM company";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                row[0]=rs.getInt("cid");
                row[1]=rs.getString("cname");
                model.addRow(row);
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblcid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        txtcname = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        lblsearch = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Company Details");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Company Table");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(380, 20, 370, 57);

        lblcid.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        lblcid.setForeground(new java.awt.Color(255, 255, 255));
        lblcid.setText("cid");
        jPanel1.add(lblcid);
        lblcid.setBounds(30, 140, 80, 43);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("company name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 210, 260, 43);
        jPanel1.add(txtcid);
        txtcid.setBounds(308, 145, 323, 30);
        jPanel1.add(txtcname);
        txtcname.setBounds(310, 220, 320, 30);

        btnsave.setBackground(new java.awt.Color(204, 204, 204));
        btnsave.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Load.png"))); // NOI18N
        btnsave.setText("save");
        btnsave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);
        btnsave.setBounds(710, 220, 130, 40);

        btnupdate.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Refresh.png"))); // NOI18N
        btnupdate.setText("Upadate");
        btnupdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), null));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(710, 290, 130, 35);

        btndelete.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Delete.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete);
        btndelete.setBounds(710, 140, 130, 37);

        lblsearch.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        lblsearch.setForeground(new java.awt.Color(255, 255, 255));
        lblsearch.setText("search by name");
        jPanel1.add(lblsearch);
        lblsearch.setBounds(30, 280, 280, 43);

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtsearch);
        txtsearch.setBounds(310, 290, 323, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cid", "company Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(49, 430, 810, 213);

        btnback.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Go back.png"))); // NOI18N
        btnback.setText("Back to Home page");
        btnback.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(320, 370, 280, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        try
        {
            String cname;
            cname=txtcname.getText();
            Connection con;
            Statement stmt;
            String uid="root";
            String pwd="";
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
            stmt=con.createStatement();
            String qry="INSERT INTO company (cname) VALUES ('"+cname+"')";
            //System.out.println(qry);
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(this,"Data Saved Successfully","Status",JOptionPane.INFORMATION_MESSAGE);
            loaddata();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
          try
        {
            String cname;
            cname=txtcname.getText();
            Connection con;
            Statement stmt;
            String uid="root";
            String pwd="";
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
            stmt=con.createStatement();
            String qry="UPDATE company SET cname='"+cname+"' WHERE cid="+Integer.parseInt(txtcid.getText());
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(this,"Data Updated succesfully","Status",JOptionPane.INFORMATION_MESSAGE);
            loaddata();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
          lblcid.setVisible(false);
        txtcid.setVisible(false);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btnsave.setEnabled(true);
        txtcname.setText("");
      
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
          int result=  JOptionPane.showConfirmDialog(this,"Are You  Suer ??","Confirmation",JOptionPane.YES_NO_OPTION);
          if(result==JOptionPane.YES_OPTION)
          {
                try
        {
             Connection con;
            Statement stmt;
            String uid="root";
            String pwd="";
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
            stmt=con.createStatement();
            String qry="DELETE FROM company WHERE cid="+Integer.parseInt(txtcid.getText());
            //System.out.println(qry);
            stmt.executeUpdate(qry);
            loaddata();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
          }
        lblcid.setVisible(false);
        txtcid.setVisible(false);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btnsave.setEnabled(true);
        txtcname.setText("");
      
    }//GEN-LAST:event_btndeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          lblcid.setVisible(true);
        txtcid.setVisible(true);
        btnupdate.setEnabled(true);
        btndelete.setEnabled(true);
        btnsave.setEnabled(false);
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        txtcid.setText(model.getValueAt(i,0).toString());
        txtcname.setText(model.getValueAt(i,1).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
     jTable1.setModel(model);
     model.setRowCount(0);
     Object row[]=new Object[2];
     try
        {
            Connection con;
            Statement stmt;
            String uid="root";
            String pwd="";
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
            stmt=con.createStatement();
            String qry="SELECT * FROM company WHERE cname LIKE '%"+txtsearch.getText()+"%'";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                row[0]=rs.getInt("cid");
                row[1]=rs.getString("cname");
              
                model.addRow(row);
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        } 
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
         Homepage h=new Homepage();
               h.setVisible(true);
               dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcid;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
