/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salemenu = new javax.swing.JMenuItem();
        jMenucompany = new javax.swing.JMenu();
        commpanyEntry = new javax.swing.JMenuItem();
        jMenumedicine = new javax.swing.JMenu();
        medicineEntry = new javax.swing.JMenuItem();
        stock = new javax.swing.JMenu();
        stockpurchase = new javax.swing.JMenuItem();
        stockavai = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME PAGE");
        setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(1279, 1543, 629, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/happy-pills_00432273.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel2.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1366, 1050);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Toolbox.png"))); // NOI18N
        jMenu1.setText("Bill");
        jMenu1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jMenu1.add(jSeparator1);

        salemenu.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        salemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/List.png"))); // NOI18N
        salemenu.setText("Bill Generate");
        salemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salemenuActionPerformed(evt);
            }
        });
        jMenu1.add(salemenu);

        jMenuBar1.add(jMenu1);

        jMenucompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Boss.png"))); // NOI18N
        jMenucompany.setText("company       ");
        jMenucompany.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jMenucompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenucompanyActionPerformed(evt);
            }
        });

        commpanyEntry.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        commpanyEntry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Company.png"))); // NOI18N
        commpanyEntry.setText("Company Entry");
        commpanyEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commpanyEntryActionPerformed(evt);
            }
        });
        jMenucompany.add(commpanyEntry);

        jMenuBar1.add(jMenucompany);

        jMenumedicine.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenumedicine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Retort.png"))); // NOI18N
        jMenumedicine.setText("Medicine       ");
        jMenumedicine.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N

        medicineEntry.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        medicineEntry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Script.png"))); // NOI18N
        medicineEntry.setText("Medicine Entry");
        medicineEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineEntryActionPerformed(evt);
            }
        });
        jMenumedicine.add(medicineEntry);

        jMenuBar1.add(jMenumedicine);

        stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Database.png"))); // NOI18N
        stock.setText("Stock        ");
        stock.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N

        stockpurchase.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        stockpurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Accounting.png"))); // NOI18N
        stockpurchase.setText("Stock purchase");
        stockpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockpurchaseActionPerformed(evt);
            }
        });
        stock.add(stockpurchase);

        stockavai.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        stockavai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Table.png"))); // NOI18N
        stockavai.setText("Stock available");
        stockavai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockavaiActionPerformed(evt);
            }
        });
        stock.add(stockavai);

        jMenuBar1.add(stock);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Help book 3d.png"))); // NOI18N
        jMenu6.setText("Help      ");
        jMenu6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgForProject/Exit.png"))); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stockavaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockavaiActionPerformed
        // TODO add your handling code here:
        stockAvailable sa= new stockAvailable();
        sa.setVisible(true);
        dispose();
    }//GEN-LAST:event_stockavaiActionPerformed

    private void jMenucompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenucompanyActionPerformed
        // TODO add your handling code here:
//         company c =new company();
//        c.setVisible(true);
    }//GEN-LAST:event_jMenucompanyActionPerformed

    private void commpanyEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commpanyEntryActionPerformed
        // TODO add your handling code here:
           company c =new company();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_commpanyEntryActionPerformed

    private void medicineEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineEntryActionPerformed
        // TODO add your handling code here:
        Medicine m= new Medicine();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_medicineEntryActionPerformed

    private void stockpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockpurchaseActionPerformed
        // TODO add your handling code here:
        stockPurchase sp= new stockPurchase();
        sp.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_stockpurchaseActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void salemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salemenuActionPerformed
        // TODO add your handling code here:
            sale s =new sale();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_salemenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem commpanyEntry;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenucompany;
    private javax.swing.JMenu jMenumedicine;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem medicineEntry;
    private javax.swing.JMenuItem salemenu;
    private javax.swing.JMenu stock;
    private javax.swing.JMenuItem stockavai;
    private javax.swing.JMenuItem stockpurchase;
    // End of variables declaration//GEN-END:variables
}
