
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class sale extends javax.swing.JFrame {

    /**
     * Creates new form sale
     */
    public sale() {
        initComponents();
         btn_remove.setEnabled(false);
         BtnPrintInvoice.setEnabled(false);
         invoice();
        // initalize();
       // loaddata();
    }
//    public void initalize()
//    {
//        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(".png")));
//    }
    
       public void invoice()
    {
        try
    {
        Connection con;
    Statement stmt;
    String uid="root",code;
        String pwd="";
        int invoice_no;
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
        stmt=con.createStatement();
        String qry="select max(invoice_no) as last_no from item_sale_amt";
           ResultSet rs=stmt.executeQuery(qry);
           if(rs.next())
           {
                invoice_no = rs.getInt("last_no")+1;             
                lbl_invoice.setText(""+invoice_no);// TODO add your handling code here:
           }
           else
           {
               lbl_invoice.setText("0");
           }
    }                                     
   catch(Exception e)
   {
   }  
    }
//     public void loaddata() {
//        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
//        jTable2.setModel(model);
//        model.setRowCount(0);
//        Object row[] = new Object[7];
//        try {
//            Connection con;
//
//            Statement stmt;
//            String uid = "root";
//            String pwd = "";
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pharma", uid, pwd);
//            stmt = con.createStatement();
//            String qry = "SELECT *,md.mname From Stock_purchase sp,medicine md WHERE md.mid=sp.mid";
//            
//            System.out.println(qry);
//            ResultSet rs = stmt.executeQuery(qry);
//            while (rs.next()) {
//                row[0] = rs.getInt("stockid");
//                row[1] = rs.getString("stockcode");
//                row[2] = rs.getString("mname");
//                //row[3] = rs.getDouble("stock_total_price");
//                row[3] = rs.getInt("sqty");
//                row[4] = rs.getString("s_mfg");
//                row[5] = rs.getString("s_exp");
//               // row[7] = rs.getString("s_date");
//                row[6] = rs.getInt("batch_no");
//                
//                model.addRow(row);
//            }
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
 //    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcustomer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        lbl_invoice = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbl_rows = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        saletable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        btn_remove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_grand_ttl = new javax.swing.JLabel();
        lbl_cgst = new javax.swing.JLabel();
        lbl_sgst = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_print_invoice = new javax.swing.JLabel();
        BtnPrintInvoice = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 153));
        jPanel1.setMaximumSize(null);
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Costmer Name");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bill no./Invoice no");

        txtcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomerActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact");

        btnsave.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnsave.setText("save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search ");

        txtsearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsearchCaretUpdate(evt);
            }
        });

        lbl_invoice.setText("*");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock Id", "Stock Code", "Medicine Name", "Medicine Price", "Stock mfg", "Stock exp", "Batch no"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        lbl_rows.setText("0");

        saletable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine code", "Medicine Name", "price", "Quantity", "Amount"
            }
        ));
        saletable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saletableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(saletable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");

        btn_remove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CGST");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SGST");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Grand Total");

        lbl_total.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("9%");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("9%");

        lbl_grand_ttl.setText("0000");

        lbl_cgst.setText("00");

        lbl_sgst.setText("000");

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("BE HEALTHY CEMIST SHOP");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("SHANKAR NAGAR NEAR TRUNING POINT, CONTACT- O771-242635");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lbl_print_invoice.setText("***");

        BtnPrintInvoice.setText("Print Invoce");
        BtnPrintInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintInvoiceActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lbl_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(lbl_print_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(78, 78, 78)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(lbl_rows, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BtnPrintInvoice))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(btn_remove)
                                                .addGap(24, 24, 24)
                                                .addComponent(jButton1)))
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_sgst, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel16))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_cgst, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(37, 37, 37)
                                                .addComponent(lbl_grand_ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(54, 54, 54)
                                                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 418, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_print_invoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_invoice)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_remove)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_rows)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsave)
                            .addComponent(BtnPrintInvoice))
                        .addGap(65, 65, 65))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lbl_cgst, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sgst)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lbl_grand_ttl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbl_total))
                        .addGap(64, 64, 64)))
                .addContainerGap(465, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtcustomerActionPerformed

    private void txtsearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtsearchCaretUpdate
        // TODO add your handling code here:
          DefaultTableModel model=(DefaultTableModel) jTable2.getModel();    
     jTable2.setModel(model);
     model.setRowCount(0);
     Object row[]=new Object[7];
     try
        {
            Connection con;
            Statement stmt;
            String uid="root";
            String pwd="";
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
            stmt=con.createStatement();
            //String qry="SELECT * FROM stock_available  WHERE mid="+Integer.parseInt(txtsearch.getText());
           // String qry="SELECT * FROM stock_purchase WHERE mid in(SELECT mid from medicine where mname like '%"+txtsearch.getText()+"%')";
           //String qry = "SELECT sp.stockid,sp.stockcode, sp.stock_total_price ,sp.sqty,sp.s_mfg,sp.s_exp,sp.s_date,md.mname,sp.batch_no From Stock_purchase sp,medicine md WHERE md.mid=sp.mid, AND md.mname like '%"+txtsearch.getText()+"%'";
            String qry = "SELECT *, md.medicineprice,md.mname From Stock_purchase sp,medicine md WHERE md.mid=sp.mid AND md.mname like '%"+txtsearch.getText()+"%'";
            //System.out.println(qry);
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                row[0]=rs.getInt("stockid");
                row[1]=rs.getString("stockcode");
                row[2]=rs.getString("mname");
               // row[3]=rs.getDouble("stock_total_price");
                row[3]=rs.getInt("medicineprice");
                row[4]=rs.getString("s_mfg");
                row[5]=rs.getString("s_exp");
                //row[7]=rs.getString("s_date");
                row[6]=rs.getInt("batch_no");
                model.addRow(row);
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_txtsearchCaretUpdate

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i =jTable2.getSelectedRow();
        TableModel model=jTable2.getModel();
        
        String name,code;
        double price,price_qty;
        int qty,ttl_rows;
        
        code=model.getValueAt(i,1).toString();
        name=model.getValueAt(i,2).toString();
        price=Double.parseDouble(model.getValueAt(i,3).toString());
        qty= Integer.parseInt(txtqty.getText());
        price_qty=qty*price;
        ttl_rows=Integer.parseInt(lbl_rows.getText());
        ttl_rows=ttl_rows+1;
        lbl_rows.setText(""+ttl_rows);
        
        //add row to second table
         
        DefaultTableModel sale_model= (DefaultTableModel)saletable.getModel();
        saletable.setModel(sale_model);
        Object row[]=new Object[5];
        row[0]=code;
       row[1]=name;
       row[2]=price;
       row[3]=qty;
       row[4]=price_qty;
       
       sale_model.addRow(row);
 
       
       //calculaton part
       double ttl,cgst,sgst,grand_ttl;
       ttl= Double.parseDouble(lbl_total.getText())+price_qty;
       
       cgst=ttl*0.09;
       sgst=ttl*0.09;
       
       grand_ttl=ttl+cgst+sgst;
       lbl_total.setText(""+ttl);
       lbl_cgst.setText(""+cgst);
       lbl_sgst.setText(""+sgst);
       lbl_grand_ttl.setText(""+grand_ttl);
       
       
       
    
        
        
        
        
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1PropertyChange

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        int ttl_rows,i;
        ttl_rows= Integer.parseInt(lbl_rows.getText());
        DefaultTableModel sale_table_model= (DefaultTableModel)saletable.getModel();
        i = saletable.getSelectedRow();
        if(i != -1)
        {
            //calculation part
            double price_qty,ttl,cgst,sgst,grand_ttl;
            price_qty = Double.parseDouble(sale_table_model.getValueAt(i, 3).toString());
            ttl = Double.parseDouble(lbl_total.getText()) - price_qty;

            cgst = ttl * 0.09;
            sgst = ttl * 0.09;

            grand_ttl = ttl + cgst + sgst;
            lbl_total.setText(""+ttl);
            lbl_cgst.setText(""+cgst);
            lbl_sgst.setText(""+sgst);
            lbl_grand_ttl.setText(""+grand_ttl);
            
            //remove selected row from the model            
            sale_table_model.removeRow(saletable.getSelectedRow());            
            ttl_rows = ttl_rows - 1;
            lbl_rows.setText(""+ttl_rows);
        }
//        if(saletable.getSelectedRow()!=1)
//        {
//            //remove selected row from the model
//           sale_table_model.removeRow(saletable.getSelectedRow());
//           ttl_rows=ttl_rows-1;
//           lbl_rows.setText(""+ttl_rows);
//        
//        }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
         int i, rows, qty, inv_no, status=0;
        String name,q_insert, q_insert_2, customer, address,code;
        Long mobile;
        double price, price_qty, ttl, cgst, sgst, grandttl;
        
        Connection con;
        Statement stmt;
        String uid="root";
        String pwd="";        
        
        inv_no = Integer.parseInt(lbl_invoice.getText());
        customer = txtcustomer.getText();
        mobile = Long.parseLong(txtcontact.getText());
        address = txtaddress.getText();
        
         ttl = Double.parseDouble(lbl_total.getText());
        cgst = Double.parseDouble(lbl_cgst.getText());
        sgst = Double.parseDouble(lbl_sgst.getText());
        grandttl = Double.parseDouble(lbl_grand_ttl.getText());
        rows = Integer.parseInt(lbl_rows.getText());        
        
        TableModel s_model = saletable.getModel();
        
        try
        {
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
                           
                for(i=0; i<rows; i++)
                {
                    code = s_model.getValueAt(i,0).toString();
                    name = s_model.getValueAt(i,1).toString();
                    price = Double.parseDouble(s_model.getValueAt(i,2).toString());
                    qty = Integer.parseInt(s_model.getValueAt(i,3).toString());
                    price_qty = Double.parseDouble(s_model.getValueAt(i,4).toString());
                    System.out.println("1");

                    q_insert = "INSERT INTO itemsale(invoice_no,item_name,price,qty,price_qty) "
                            + " VALUES("+inv_no+",'"+name+"',"+price+","+qty+","+price_qty+")";   
             
                    //System.out.println(q_insert);
                    stmt=con.createStatement();
                    stmt.executeUpdate(q_insert);
                    
                   
                    String q_up = "update stock_available set sqty=sqty-"+qty+" where stockcode='"+code+"'";
                    stmt=con.createStatement();
                    stmt.executeUpdate(q_up);           
                }
                
                if(i==rows)
                {
                    q_insert_2 = "INSERT INTO item_sale_amt(invoice_no, customer_name, mobile, address, total, cgst, sgst, grandttl, invoice_date) "
                            + " VALUES("+inv_no+",'"+customer+"',"+mobile+",'"+address+"',"+ttl+","+cgst+","+sgst+","+grandttl+",date(now()))";
                    //System.out.println(q_insert_2);
                    stmt=con.createStatement();
                    stmt.executeUpdate(q_insert_2);
                    status++;
                }
                if(status!=0)
                {
                    JOptionPane.showMessageDialog(this, rows+" Items Sold","status",JOptionPane.INFORMATION_MESSAGE);
                    lbl_print_invoice.setText(""+inv_no);
                    BtnPrintInvoice.setEnabled(true);
                    invoice();
                }
        }
         catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
//        int rows,qty;
//        String name;
//        double price,price_qty;
//        rows= Integer.parseInt(lbl_rows.getText());
//        TableModel s_model= saletable.getModel();
//        
//        for(int i=0;i<rows;i++)
//        {
//            name= s_model.getValueAt(i,0).toString();
//            price=Double.parseDouble(s_model.getValueAt(i,0).toString());
//            qty=Integer.parseInt(s_model.getValueAt(i,2).toString());
//            price_qty=Double.parseDouble(s_model.getValueAt(i,3).toString());
//            System.out.println(name);
//            
//        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void saletableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saletableMouseClicked
        // TODO add your handling code here:
        btn_remove.setEnabled(true);
    }//GEN-LAST:event_saletableMouseClicked

    private void BtnPrintInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintInvoiceActionPerformed
        // TODO add your handling code here:
        int inv_no, i, rows, itemqty;
        long mobile;
        String cur_dt, invoicefile, sb_to_str, itemname, customer, address;
        double itemprice,pr_qty,ttl,cgst,sgst,grandttl;
        
        //fetch data from controls
        inv_no = Integer.parseInt(lbl_print_invoice.getText());
        
        //current date 
        Date dt = new Date();
        SimpleDateFormat d = new SimpleDateFormat("dd-MM-yyyy");
        cur_dt = d.format(dt);
        //System.out.println("current date : "+cur_dt);
        
        customer = txtcustomer.getText();
        mobile = Long.parseLong(txtcontact.getText());
        address = txtaddress.getText();

        //code for invoice printing
        StringBuilder s = new StringBuilder();
        s.append("\t"+"\t"+"\t"+"\t"+"BE HEALTHY CEMIST SHOP"+"\t"+"\t"+"\t"+"\t").append("\n");
        s.append("Invoice No : "+inv_no+"\t"+"\t"+"\t"+"\t"+"\t"+"Invoice date : "+cur_dt).append("\n");
        s.append("Customer Name    : "+customer).append("\n");
        s.append("Customer Contact : "+mobile).append("\n");
        s.append("Customer Address : "+address).append("\n"+"\n");
        s.append("--------------------------"+"Items Purchased"+"-----------------------------").append("\n");
        s.append("Item Name"+"\t"+"\t"+"Price"+"\t"+"\t"+"Quantity"+"\t"+"\t"+"Amount").append("\n");
        
        //sale table data fetching 
        TableModel s_model = saletable.getModel();
        rows = Integer.parseInt(lbl_rows.getText());
                for(i=0; i<rows; i++)
                {
                    itemname = s_model.getValueAt(i,1).toString();
                    itemprice = Double.parseDouble(s_model.getValueAt(i,2).toString());
                    itemqty = Integer.parseInt(s_model.getValueAt(i,3).toString());
                    pr_qty = Double.parseDouble(s_model.getValueAt(i,4).toString());
                    s.append(itemname+"\t"+"\t"+itemprice+"\t"+"\t"+itemqty+"\t"+"\t"+pr_qty).append("\n");                    
                }      
        
                s.append("-----------------------------------------------------------------").append("\n");
                
                ttl = Double.parseDouble(lbl_total.getText());
                cgst = Double.parseDouble(lbl_cgst.getText());
                sgst = Double.parseDouble(lbl_sgst.getText());
                grandttl = Double.parseDouble(lbl_grand_ttl.getText());
                
                s.append("\t"+"\t"+"\t"+"\t"+"\t"+"Total Amount : "+ttl).append("\n");
                s.append("\t"+"\t"+"\t"+"\t"+"\t"+"CGST Applied : "+cgst).append("\n");
                s.append("\t"+"\t"+"\t"+"\t"+"\t"+"SGST Applied : "+sgst).append("\n");
                s.append("\t"+"\t"+"\t"+"\t"+"\t"+"Grand Total  : "+grandttl).append("\n");
        
        invoicefile = inv_no+"_"+cur_dt;
        BufferedWriter bw;
        FileWriter fstream;
        try
        {
            fstream = new FileWriter("D:/Invoice/"+invoicefile+".txt");
            bw = new BufferedWriter(fstream);
            sb_to_str = s.toString();
            System.out.println(sb_to_str);
            //write to file
            bw.write(sb_to_str);          
            bw.close();
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
         //fetch invoicefile from the destination folder
            File f = new File("D:\\Invoice\\"+invoicefile+".txt");
            try
            {
                Desktop.getDesktop().open(f);
            }
            catch(IOException ioe)
            {
                System.out.println(ioe.getMessage());
            }
    }//GEN-LAST:event_BtnPrintInvoiceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Homepage h=new Homepage();
               h.setVisible(true);
               dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPrintInvoice;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_cgst;
    private javax.swing.JLabel lbl_grand_ttl;
    private javax.swing.JLabel lbl_invoice;
    private javax.swing.JLabel lbl_print_invoice;
    private javax.swing.JLabel lbl_rows;
    private javax.swing.JLabel lbl_sgst;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable saletable;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtcustomer;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

   // private void initComponents() {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   // }
}
