
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class stockAvailable extends javax.swing.JFrame {

    /**
     * Creates new form stockAvailable
     */
    public stockAvailable() {
        initComponents();
        loaddata();
    }
    public void loaddata()
    {
     
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        jTable1.setModel(model);
        model.setRowCount(0);
        Object row[]=new Object[9];
     try
        {
            Connection con;
            Statement stmt;
            String uid="root";
            String pwd="";
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
            stmt=con.createStatement();
            String qry="SELECT *,md.mname From Stock_available sp,medicine md WHERE md.mid=sp.mid";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                row[0]=rs.getInt("stid");
                row[1]=rs.getString("stockcode");
                row[2]=rs.getString("mname");
                row[3]=rs.getInt("sqty");
                row[4]=rs.getString("s_mfg");
                row[5]=rs.getString("s_exp");
                row[6]=rs.getString("s_date");
                row[8]=rs.getString("status");
                row[7]=rs.getInt("batch_no");
                model.addRow(row);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Available");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search by Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 126, 174, 29);

        txtsearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsearchCaretUpdate(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtsearch);
        txtsearch.setBounds(200, 122, 369, 30);

        jTable1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock id", "Stock code", "medicine id", "Stock quantity", "Stock mfg", "Stock exp", "Stock date", "Batch no", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 230, 800, 402);

        txtback.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        txtback.setText("Back to homepage");
        txtback.setBorder(null);
        txtback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbackActionPerformed(evt);
            }
        });
        jPanel1.add(txtback);
        txtback.setBounds(660, 130, 230, 25);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stock Available Table");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 13, 352, 43);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-1.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1920, 900);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtsearchCaretUpdate
        // TODO add your handling code here:  DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
             DefaultTableModel model=(DefaultTableModel) jTable1.getModel();    
     jTable1.setModel(model);
     model.setRowCount(0);
     Object row[]=new Object[9];
     try
        {
            Connection con;
            Statement stmt;
            String uid="root";
            String pwd="";
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
            stmt=con.createStatement();
            //String qry="SELECT * FROM stock_available  WHERE mid="+Integer.parseInt(txtsearch.getText());
           // String qry="SELECT * FROM stock_purchase WHERE mid in(SELECT mid from medicine where mname like '%"+txtsearch.getText()+"%')";
            String qry = "SELECT* From Stock_available sp,medicine md WHERE md.mid=sp.mid AND md.mname like '%"+txtsearch.getText()+"%'";
           // System.out.println(qry);
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                row[0]=rs.getInt("stid");
                row[1]=rs.getString("stockcode");
                row[2]=rs.getString("mname");
                row[3]=rs.getInt("sqty");
                row[4]=rs.getString("s_mfg");
                row[5]=rs.getString("s_exp");
                row[6]=rs.getString("s_date");
                row[7]=rs.getString("status");
                row[8]=rs.getInt("batch_no");
                model.addRow(row);
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
//     jTable1.setModel(model);
//     model.setRowCount(0);
//     Object row[]=new Object[9];
//     try
//        {
//            Connection con;
//            Statement stmt;
//            String uid="root";
//            String pwd="";
//            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
//            stmt=con.createStatement();
//            String qry="SELECT * FROM stock_available  WHERE mid="+Integer.parseInt(txtsearch.getText());
//            System.out.println(qry);
//            ResultSet rs=stmt.executeQuery(qry);
//            while(rs.next())
//            {
//                row[0]=rs.getInt("stid");
//                row[1]=rs.getString("stockcode");
//                row[3]=rs.getInt("mid");
//                row[2]=rs.getInt("sqty");
//                row[4]=rs.getString("s_mfg");
//                row[5]=rs.getString("s_exp");
//                row[6]=rs.getString("s_date");
//                row[7]=rs.getString("status");
//                row[8]=rs.getInt("batch_no");
//                model.addRow(row);
//                
//            }
//        }
//        catch(Exception e)
//        {
//            System.out.println(e.getMessage());
////        }
//         try
//         {
//            int mid;
//            mid=Integer.parseInt(txtsearch.getText());
//            Connection con;
//            Statement stmt;
//            String uid="root";
//            String pwd="";
//            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharma",uid,pwd);
//            stmt=con.createStatement();
//            String qry="SELECT FROM stock_available (mid,) VALUES ("+mid+")";          //System.out.println(qry);
//            stmt.executeUpdate(qry);
//            JOptionPane.showMessageDialog(this,"Data Saved Successfully","Status",JOptionPane.INFORMATION_MESSAGE);
//            loaddata();
//        }
//        catch(Exception e)
//        {
//            System.out.println(e.getMessage());
//        }
    }//GEN-LAST:event_txtsearchCaretUpdate

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbackActionPerformed
        // TODO add your handling code here:
         Homepage h=new Homepage();
               h.setVisible(true);
               dispose();
    }//GEN-LAST:event_txtbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockAvailable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockAvailable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockAvailable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockAvailable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockAvailable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton txtback;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
